/* automatically generated by rust-bindgen 0.73.2 */

#[derive(PartialEq, Eq, Copy, Clone, Debug, Hash)]
#[repr(C, align(8))]
pub struct __BindgenOpaqueArray8<T>(pub T);
impl<T: Copy + Default, const N: usize> Default for __BindgenOpaqueArray8<[T; N]> {
    fn default() -> Self {
        Self([<T as Default>::default(); N])
    }
}
unsafe extern "C" {
    #[doc = " Converts samples from an audio file into data used to display a waveform.\n\n @param samples Array of sample data from an audio file.\n @param size Length of the array.\n @param width Width of the waveform.\n @param height Height of the waveform.\n @public"]
    #[link_name = "\u{1}_ConvertSamplesToWaveform"]
    pub fn RhythmGameUtilities_ConvertSamplesToWaveform(
        samples: *const f32,
        size: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> *mut *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Free data returned from the ConvertSamplesToWaveform function.\n\n @param waveform Waveform multidimensional array.\n @param width Width of the waveform.\n @public"]
    #[link_name = "\u{1}_FreeWaveform"]
    pub fn RhythmGameUtilities_FreeWaveform(
        waveform: *mut *mut ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    #[doc = " Calculates the linear interpolation between two values.\n\n @param a The start value.\n @param b The end value.\n @param t The value used for interpolation.\n @public"]
    #[link_name = "\u{1}_Lerp"]
    pub fn RhythmGameUtilities_Lerp(a: f32, b: f32, t: f32) -> f32;
}
unsafe extern "C" {
    #[doc = " Calculates the fraction, based on a value between two values without\n clamping between 0 and 1.\n\n @param a The start value.\n @param b The end value.\n @param v The value in the middle.\n @public"]
    #[link_name = "\u{1}_InverseLerpUnclamped"]
    pub fn RhythmGameUtilities_InverseLerpUnclamped(a: f32, b: f32, v: f32) -> f32;
}
unsafe extern "C" {
    #[doc = " Calculates the fraction, based on a value between two values.\n\n @param a The start value.\n @param b The end value.\n @param v The value in the middle.\n @public"]
    #[link_name = "\u{1}_InverseLerp"]
    pub fn RhythmGameUtilities_InverseLerp(a: f32, b: f32, v: f32) -> f32;
}
pub const RhythmGameUtilities_Difficulty_Easy: RhythmGameUtilities_Difficulty = 0;
pub const RhythmGameUtilities_Difficulty_Medium: RhythmGameUtilities_Difficulty = 1;
pub const RhythmGameUtilities_Difficulty_Hard: RhythmGameUtilities_Difficulty = 2;
pub const RhythmGameUtilities_Difficulty_Expert: RhythmGameUtilities_Difficulty = 3;
pub type RhythmGameUtilities_Difficulty = u8;
pub const RhythmGameUtilities_NamedSection_Song: RhythmGameUtilities_NamedSection = 0;
pub const RhythmGameUtilities_NamedSection_SyncTrack: RhythmGameUtilities_NamedSection = 1;
pub const RhythmGameUtilities_NamedSection_Events: RhythmGameUtilities_NamedSection = 2;
pub type RhythmGameUtilities_NamedSection = u8;
pub const RhythmGameUtilities_TypeCode_BPM_Marker: RhythmGameUtilities_TypeCode = 0;
pub const RhythmGameUtilities_TypeCode_TimeSignatureMarker: RhythmGameUtilities_TypeCode = 1;
pub const RhythmGameUtilities_TypeCode_NoteMarker: RhythmGameUtilities_TypeCode = 2;
pub const RhythmGameUtilities_TypeCode_EventMarker: RhythmGameUtilities_TypeCode = 3;
pub type RhythmGameUtilities_TypeCode = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_Note {
    pub ID: ::std::os::raw::c_int,
    pub Position: ::std::os::raw::c_int,
    pub HandPosition: ::std::os::raw::c_int,
    pub Length: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_Note"]
        [::std::mem::size_of::<RhythmGameUtilities_Note>() - 16usize];
    ["Alignment of RhythmGameUtilities_Note"]
        [::std::mem::align_of::<RhythmGameUtilities_Note>() - 4usize];
    ["Offset of field: RhythmGameUtilities_Note::ID"]
        [::std::mem::offset_of!(RhythmGameUtilities_Note, ID) - 0usize];
    ["Offset of field: RhythmGameUtilities_Note::Position"]
        [::std::mem::offset_of!(RhythmGameUtilities_Note, Position) - 4usize];
    ["Offset of field: RhythmGameUtilities_Note::HandPosition"]
        [::std::mem::offset_of!(RhythmGameUtilities_Note, HandPosition) - 8usize];
    ["Offset of field: RhythmGameUtilities_Note::Length"]
        [::std::mem::offset_of!(RhythmGameUtilities_Note, Length) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_Tempo {
    pub Position: ::std::os::raw::c_int,
    pub BPM: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_Tempo"]
        [::std::mem::size_of::<RhythmGameUtilities_Tempo>() - 8usize];
    ["Alignment of RhythmGameUtilities_Tempo"]
        [::std::mem::align_of::<RhythmGameUtilities_Tempo>() - 4usize];
    ["Offset of field: RhythmGameUtilities_Tempo::Position"]
        [::std::mem::offset_of!(RhythmGameUtilities_Tempo, Position) - 0usize];
    ["Offset of field: RhythmGameUtilities_Tempo::BPM"]
        [::std::mem::offset_of!(RhythmGameUtilities_Tempo, BPM) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_TimeSignature {
    pub Position: ::std::os::raw::c_int,
    pub Numerator: ::std::os::raw::c_int,
    pub Denominator: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_TimeSignature"]
        [::std::mem::size_of::<RhythmGameUtilities_TimeSignature>() - 12usize];
    ["Alignment of RhythmGameUtilities_TimeSignature"]
        [::std::mem::align_of::<RhythmGameUtilities_TimeSignature>() - 4usize];
    ["Offset of field: RhythmGameUtilities_TimeSignature::Position"]
        [::std::mem::offset_of!(RhythmGameUtilities_TimeSignature, Position) - 0usize];
    ["Offset of field: RhythmGameUtilities_TimeSignature::Numerator"]
        [::std::mem::offset_of!(RhythmGameUtilities_TimeSignature, Numerator) - 4usize];
    ["Offset of field: RhythmGameUtilities_TimeSignature::Denominator"]
        [::std::mem::offset_of!(RhythmGameUtilities_TimeSignature, Denominator) - 8usize];
};
unsafe extern "C" {
    #[link_name = "\u{1}__ZN19RhythmGameUtilities16parsedChartCacheE"]
    pub static mut RhythmGameUtilities_parsedChartCache: __BindgenOpaqueArray8<[u8; 24usize]>;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadResolutionFromChartData"]
    pub fn RhythmGameUtilities_ReadResolutionFromChartData(
        contents: *const ::std::os::raw::c_char,
    ) -> u16;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadTempoChangesFromChartDataInternal"]
    pub fn RhythmGameUtilities_ReadTempoChangesFromChartDataInternal(
        contents: *const ::std::os::raw::c_char,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_Tempo;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadTimeSignatureChangesFromChartDataInternal"]
    pub fn RhythmGameUtilities_ReadTimeSignatureChangesFromChartDataInternal(
        contents: *const ::std::os::raw::c_char,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_TimeSignature;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadNotesFromChartDataInternal"]
    pub fn RhythmGameUtilities_ReadNotesFromChartDataInternal(
        contents: *const ::std::os::raw::c_char,
        difficulty: RhythmGameUtilities_Difficulty,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_Note;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_ByteStream {
    pub data: *const u8,
    pub size: usize,
    pub pos: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_ByteStream"]
        [::std::mem::size_of::<RhythmGameUtilities_ByteStream>() - 24usize];
    ["Alignment of RhythmGameUtilities_ByteStream"]
        [::std::mem::align_of::<RhythmGameUtilities_ByteStream>() - 8usize];
    ["Offset of field: RhythmGameUtilities_ByteStream::data"]
        [::std::mem::offset_of!(RhythmGameUtilities_ByteStream, data) - 0usize];
    ["Offset of field: RhythmGameUtilities_ByteStream::size"]
        [::std::mem::offset_of!(RhythmGameUtilities_ByteStream, size) - 8usize];
    ["Offset of field: RhythmGameUtilities_ByteStream::pos"]
        [::std::mem::offset_of!(RhythmGameUtilities_ByteStream, pos) - 16usize];
};
pub const RhythmGameUtilities_META_EVENT: ::std::os::raw::c_int = 255;
pub const RhythmGameUtilities_END_OF_TRACK: ::std::os::raw::c_int = 47;
pub const RhythmGameUtilities_SYSTEM_COMMAND: ::std::os::raw::c_int = 240;
pub const RhythmGameUtilities_TEMPO_CHANGE: ::std::os::raw::c_int = 81;
pub const RhythmGameUtilities_TIME_SIGNATURE_CHANGE: ::std::os::raw::c_int = 88;
pub const RhythmGameUtilities_NOTE_ON_COMMAND: ::std::os::raw::c_int = 144;
pub const RhythmGameUtilities_PROGRAM_CHANGE_COMMAND: ::std::os::raw::c_int = 192;
pub const RhythmGameUtilities_CHANNEL_PRESSURE_COMMAND: ::std::os::raw::c_int = 208;
pub const RhythmGameUtilities_MidiEventType_Meta: RhythmGameUtilities_MidiEventType = 0;
pub const RhythmGameUtilities_MidiEventType_NoteOn: RhythmGameUtilities_MidiEventType = 1;
pub type RhythmGameUtilities_MidiEventType = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_MidiHeader {
    pub length: u32,
    pub format: u16,
    pub trackCount: u16,
    pub resolution: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_MidiHeader"]
        [::std::mem::size_of::<RhythmGameUtilities_MidiHeader>() - 12usize];
    ["Alignment of RhythmGameUtilities_MidiHeader"]
        [::std::mem::align_of::<RhythmGameUtilities_MidiHeader>() - 4usize];
    ["Offset of field: RhythmGameUtilities_MidiHeader::length"]
        [::std::mem::offset_of!(RhythmGameUtilities_MidiHeader, length) - 0usize];
    ["Offset of field: RhythmGameUtilities_MidiHeader::format"]
        [::std::mem::offset_of!(RhythmGameUtilities_MidiHeader, format) - 4usize];
    ["Offset of field: RhythmGameUtilities_MidiHeader::trackCount"]
        [::std::mem::offset_of!(RhythmGameUtilities_MidiHeader, trackCount) - 6usize];
    ["Offset of field: RhythmGameUtilities_MidiHeader::resolution"]
        [::std::mem::offset_of!(RhythmGameUtilities_MidiHeader, resolution) - 8usize];
};
unsafe extern "C" {
    #[link_name = "\u{1}_ReadResolutionFromMidiDataInternal"]
    pub fn RhythmGameUtilities_ReadResolutionFromMidiDataInternal(
        data: *const u8,
        dataSize: ::std::os::raw::c_int,
    ) -> u16;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadTempoChangesFromMidiDataInternal"]
    pub fn RhythmGameUtilities_ReadTempoChangesFromMidiDataInternal(
        data: *const u8,
        dataSize: ::std::os::raw::c_int,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_Tempo;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadTimeSignatureChangesFromMidiDataInternal"]
    pub fn RhythmGameUtilities_ReadTimeSignatureChangesFromMidiDataInternal(
        data: *const u8,
        dataSize: ::std::os::raw::c_int,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_TimeSignature;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ReadNotesFromMidiDataInternal"]
    pub fn RhythmGameUtilities_ReadNotesFromMidiDataInternal(
        data: *const u8,
        dataSize: ::std::os::raw::c_int,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_Note;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RhythmGameUtilities_BeatBar {
    pub Position: ::std::os::raw::c_int,
    pub BPM: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RhythmGameUtilities_BeatBar"]
        [::std::mem::size_of::<RhythmGameUtilities_BeatBar>() - 8usize];
    ["Alignment of RhythmGameUtilities_BeatBar"]
        [::std::mem::align_of::<RhythmGameUtilities_BeatBar>() - 4usize];
    ["Offset of field: RhythmGameUtilities_BeatBar::Position"]
        [::std::mem::offset_of!(RhythmGameUtilities_BeatBar, Position) - 0usize];
    ["Offset of field: RhythmGameUtilities_BeatBar::BPM"]
        [::std::mem::offset_of!(RhythmGameUtilities_BeatBar, BPM) - 4usize];
};
unsafe extern "C" {
    #[link_name = "\u{1}_FreeBeatBars"]
    pub fn RhythmGameUtilities_FreeBeatBars(beatBars: *mut RhythmGameUtilities_BeatBar);
}
unsafe extern "C" {
    #[link_name = "\u{1}_FreeTempoChanges"]
    pub fn RhythmGameUtilities_FreeTempoChanges(tempoChanges: *mut RhythmGameUtilities_Tempo);
}
unsafe extern "C" {
    #[link_name = "\u{1}_FreeTimeSignatureChanges"]
    pub fn RhythmGameUtilities_FreeTimeSignatureChanges(
        timeSignatureChanges: *mut RhythmGameUtilities_TimeSignature,
    );
}
unsafe extern "C" {
    #[link_name = "\u{1}_FreeNotes"]
    pub fn RhythmGameUtilities_FreeNotes(notes: *mut RhythmGameUtilities_Note);
}
pub const RhythmGameUtilities_Accuracy_Invalid: RhythmGameUtilities_Accuracy = 0;
pub const RhythmGameUtilities_Accuracy_Poor: RhythmGameUtilities_Accuracy = 1;
pub const RhythmGameUtilities_Accuracy_Fair: RhythmGameUtilities_Accuracy = 2;
pub const RhythmGameUtilities_Accuracy_Good: RhythmGameUtilities_Accuracy = 3;
pub const RhythmGameUtilities_Accuracy_Great: RhythmGameUtilities_Accuracy = 4;
pub const RhythmGameUtilities_Accuracy_Perfect: RhythmGameUtilities_Accuracy = 5;
pub type RhythmGameUtilities_Accuracy = u8;
pub const RhythmGameUtilities_Timing_Miss: RhythmGameUtilities_Timing = 0;
pub const RhythmGameUtilities_Timing_Hit: RhythmGameUtilities_Timing = 1;
pub const RhythmGameUtilities_Timing_Early: RhythmGameUtilities_Timing = 2;
pub const RhythmGameUtilities_Timing_Late: RhythmGameUtilities_Timing = 3;
pub type RhythmGameUtilities_Timing = u8;
pub const RhythmGameUtilities_SECONDS_PER_MINUTE: f32 = 60.0;
pub const RhythmGameUtilities_MILLISECONDS: f32 = 1000.0;
pub const RhythmGameUtilities_DEFAULT_TICK_DELTA: ::std::os::raw::c_int = 50;
unsafe extern "C" {
    #[doc = " Calculate ticks per second.\n\n @param bpm The base BPM for a song.\n @param resolution The resolution of the song.\n @public"]
    #[link_name = "\u{1}_CalculateTicksPerSecond"]
    pub fn RhythmGameUtilities_CalculateTicksPerSecond(
        bpm: ::std::os::raw::c_int,
        resolution: ::std::os::raw::c_int,
    ) -> f32;
}
unsafe extern "C" {
    #[doc = " Convert a tick to a 2D/3D position.\n\n @param tick The tick.\n @param resolution The resolution of the song.\n @public"]
    #[link_name = "\u{1}_ConvertTickToPosition"]
    pub fn RhythmGameUtilities_ConvertTickToPosition(
        tick: ::std::os::raw::c_int,
        resolution: ::std::os::raw::c_int,
    ) -> f32;
}
unsafe extern "C" {
    #[doc = " Checks to see if the current time of a game or audio file is on the beat.\n\n @param bpm The base BPM for a song.\n @param currentTime A timestamp to compare to the BPM.\n @param delta The plus/minus delta to test the current time against.\n @public"]
    #[link_name = "\u{1}_IsOnTheBeat"]
    pub fn RhythmGameUtilities_IsOnTheBeat(
        bpm: ::std::os::raw::c_int,
        currentTime: f32,
        delta: f32,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Rounds a value up the nearest multiplier.\n\n @param value The value to round.\n @param multiplier The multiplier to round using.\n @public"]
    #[link_name = "\u{1}_RoundUpToTheNearestMultiplier"]
    pub fn RhythmGameUtilities_RoundUpToTheNearestMultiplier(
        value: ::std::os::raw::c_int,
        multiplier: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Calculated the accuracy ratio of the current position against a static\n position.\n\n @param position The position to test against.\n @param currentPosition The current position.\n @param delta The plus/minus delta to test the current position against.\n @public"]
    #[link_name = "\u{1}_CalculateAccuracyRatio"]
    pub fn RhythmGameUtilities_CalculateAccuracyRatio(
        position: ::std::os::raw::c_int,
        currentPosition: ::std::os::raw::c_int,
        delta: ::std::os::raw::c_int,
    ) -> f32;
}
unsafe extern "C" {
    #[link_name = "\u{1}_CalculateAccuracy"]
    pub fn RhythmGameUtilities_CalculateAccuracy(
        position: ::std::os::raw::c_int,
        currentPosition: ::std::os::raw::c_int,
        delta: ::std::os::raw::c_int,
    ) -> RhythmGameUtilities_Accuracy;
}
unsafe extern "C" {
    #[link_name = "\u{1}_CalculateTiming"]
    pub fn RhythmGameUtilities_CalculateTiming(
        position: ::std::os::raw::c_int,
        currentPosition: ::std::os::raw::c_int,
        delta: ::std::os::raw::c_int,
    ) -> RhythmGameUtilities_Timing;
}
unsafe extern "C" {
    #[link_name = "\u{1}_ConvertSecondsToTicksInternal"]
    pub fn RhythmGameUtilities_ConvertSecondsToTicksInternal(
        seconds: f32,
        resolution: ::std::os::raw::c_int,
        tempoChanges: *mut RhythmGameUtilities_Tempo,
        tempoChangesSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "\u{1}_CalculateBeatBarsInternal"]
    pub fn RhythmGameUtilities_CalculateBeatBarsInternal(
        tempoChanges: *mut RhythmGameUtilities_Tempo,
        tempoChangesSize: ::std::os::raw::c_int,
        resolution: ::std::os::raw::c_int,
        includeHalfNotes: bool,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_BeatBar;
}
unsafe extern "C" {
    #[link_name = "\u{1}_FindNotesNearGivenTickInternal"]
    pub fn RhythmGameUtilities_FindNotesNearGivenTickInternal(
        notes: *mut RhythmGameUtilities_Note,
        noteSize: ::std::os::raw::c_int,
        tick: ::std::os::raw::c_int,
        delta: ::std::os::raw::c_int,
        outSize: *mut ::std::os::raw::c_int,
    ) -> *mut RhythmGameUtilities_Note;
}
