name: Publish NPM Package

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-javascript:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install Emscripten
        uses: HandcrankEngine/install-emscripten-package@d578b50f8f7f76ea25c14b13b7df943b31e37891 # v0.3.1

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Update NPM to latest
        run: npm install npm@latest -g

      - name: Print Node.js and NPM version
        run: |
          node -v
          npm -v

      - name: Install dependencies
        working-directory: JavaScriptPackage/
        run: npm ci --ignore-scripts

      - name: Build package
        working-directory: JavaScriptPackage/
        run: npm run build

      - name: Publish package
        working-directory: JavaScriptPackage/
        run: npm publish --tag=alpha --provenance --access public
